### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::hasPermission()

### ISSUE THREAD

**Issue by aketai** [stevebauman/administration#9]
After setup:
BadMethodCallException in Builder.php line 2161:
Call to undefined method Illuminate\Database\Query\Builder::hasPermission()

**Comment by stevebauman** [comment]
You need to insert the `Stevebauman\Authorization\Traits\UserRolesTrait` onto your `User` model.

**Comment by aketai** [comment]
Which User? Have two: 1. App\User 2. App\Models\User - where Stevebauman\Authorization\Traits\UserRolesTrait already exist

**Comment by stevebauman** [comment]
You only need one, by default this package publishes a `User` model in the `app/Models/` directory. You can delete it if you'd prefer to use your own.

Then you need to configure the model you'd like to use in your `config/auth.php` file.

**Comment by aketai** [comment]
Ok. Done! Thank you
